# Generated by Django 3.1.3 on 2020-11-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.ManyToManyField(related_name='user', to='movies.Genre'),
        ),
    ]
