# Generated by Django 3.1.3 on 2020-11-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_likemovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
    ]
