# Generated by Django 3.1.3 on 2020-11-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_likemovie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeMovie',
        ),
    ]
