# Generated by Django 3.1.3 on 2020-11-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_likemovie'),
        ('movies', '0005_remove_movie_release_date'),
    ]

    operations = [
    ]
